### ISSUE TITLE
if possible change swift package dependency to pods

### ISSUE THREAD

**Issue by luffyjie** [Bartozo/Life-Progress-iOS#2]
I want to give an ideal that swift package make  is a bullshit tools. Thanks for sharing this swift project, it is gorgeous. But I failed running it, package cannot download totally success.

**Comment by Bartozo** [comment]
👋 Hello there

Thank you for trying out the Life Progress app, and I appreciate your feedback. It is great to hear that you find the project interesting. I am sorry to hear that you encountered difficulties while using Swift Package Manager (SPM). 

Firstly, I want to clarify that I don't plan to use CocoaPods as an alternative, so we will focus on making SPM work for you. Here are some steps to address the problem: ⬇️

1) **Resetting the Xcode Package Cache**: To reset the package cache, go to the "File" menu in Xcode, navigate to "Packages," and select "Reset Package Caches." This action will remove all local package data and then re-download each package from its original online source.

2) **Cleaning the Build Folder**: Another helpful step is to clean your project's build folder. You can do this by accessing the "Product" menu in Xcode and choosing "Clean Build Folder." This action clears the partial build caches, ensuring that your next build starts without any pre-compiled artifacts. Sometimes, this can also assist in resolving issues you might be facing.

I hope these steps prove helpful in resolving the challenges you have encountered with Swift Package Manager. If you run into any specific error messages or encounter further issues during this process, please don't hesitate to share them. Thank you for your patience and collaboration. 🙌

Best regards,
Bartozo

**Comment by Bartozo** [comment]
I am closing the GitHub issue due to inactivity. It has been a while without updates. If you still need help or have new info, please feel free to open a new issue anytime.

Best regards,
Bartozo
